'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createGameServer}=require('../server/index.cjs'),R=require('../shared/regions.js'),E=require('../shared/ecology.js');
const out=path.join(__dirname,'../test-output');fs.mkdirSync(out,{recursive:true});
const game=createGameServer({rng:()=>.1,authority:{verifyToken:async token=>({uid:token}),getRoom:async()=>({gameType:'insectExpedition',status:'playing',players:{alice:{nickname:'하나'}}})},dbPath:path.join(fs.mkdtempSync(path.join(os.tmpdir(),'ecology-ui-')),'db.json')});let browser,page;
(async()=>{try{
 const profile=game.store.get('alice');profile.adventurerName='하나';profile.characterCreated=true;profile.regionId='forest';profile.location=R.spawn('forest');for(const k of ['sap','pollen','mushroom','berries','ore','essence','crystal'])profile.resources[k]=20;profile.collection[0].speciesId='moon_moth';profile.collection[0].level=20;profile.collection[0].hp=null;profile.collection[1].speciesId=profile.collection[2].speciesId='king_stag';profile.collection[1].level=profile.collection[2].level=26;profile.collection.push(game.store.createCreature('king_stag',5));profile.resources.shard=6;profile.mounts={owned:['motorcycle'],equipped:'motorcycle'};game.store.save(profile);
 const address=await game.listen(0,'127.0.0.1');browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const errors=[];
 await context.route('https://www.gstatic.com/firebasejs/**',route=>route.fulfill({contentType:'text/javascript',body:`window.firebase ||= {apps:[{}],auth:()=>({onAuthStateChanged(fn){queueMicrotask(()=>fn({uid:'alice',getIdToken:async()=> 'alice'}));return ()=>{};}}),database:()=>({ref:()=>({once:async()=>({val:()=>({gameType:'insectExpedition',status:'playing',players:{alice:{nickname:'하나'}}})})})})};`}));
 page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.log('브라우저 오류',e.stack);});page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:'+address.port+'/insect_expedition/index.html?roomId=eco-ui');let f=await(await page.locator('#game-frame').elementHandle()).contentFrame();await f.waitForFunction(()=>window.InsectApp?.ready,null,{timeout:60000});await f.locator('[data-act="customize"]').waitFor();
 const room=game.rooms.get('isulsup-public'),player=room.players.get('alice');async function click(selector){await f.locator(selector).first().click();await page.waitForTimeout(600);}async function shot(name){await page.screenshot({path:path.join(out,'ecology-'+name+'.png')});}
 async function move(p){player.x=p.x;player.z=p.z;await f.waitForFunction(pos=>{const s=InsectApp.getSnapshot(),p=s.players.find(p=>p.uid===s.you);return Math.hypot(p.x-pos.x,p.z-pos.z)<1;},p);await page.waitForTimeout(1000);}
 await page.waitForTimeout(1500);assert(await f.evaluate(()=>InsectApp.getSnapshot().spawns.length>=35));await shot('forest-entry');
 console.log('입구 화면 및 출현 확인');
 await click('[data-value="ecology"]');await click('.eco-intro [data-value="research"]');await click('[data-act="panel-back"]');assert(await f.locator('.ix-ecology-drawer').count());await f.locator('[data-act="panel-back"]').focus();await page.keyboard.press('Escape');assert.equal(await f.locator('.ix-drawer').count(),0);
 await click('[data-value="ecology"]');await click('[data-act="trial-start"][data-id="1"]');await f.waitForFunction(()=>!!InsectApp.getSnapshot().battle?.trial);await f.evaluate(()=>InsectApp.send('auto-battle',{enabled:false}));const trial=room.battles.get(player.battleId);trial.state.sides.b.team.forEach(c=>{c.hp=1;c.attack=1;});trial.state.sides.a.team.forEach(c=>{c.speed=999;c.hp=c.maxHp;c.attack=999;});await shot('trial-battle');for(let i=0;i<8&&trial.state.status==='active';i++){await f.waitForFunction(()=>!InsectApp.isAnimating(),null,{timeout:20000});await click('[data-action="attack"]');}await f.waitForFunction(()=>!InsectApp.isAnimating()&&InsectApp.getSnapshot().battle.status==='finished',null,{timeout:20000});await click('[data-act="return"]');assert.equal(player.profile.trials.cleared,1);
 await click('[data-value="collection"]');const first=player.profile.collection[0],extra=player.profile.collection.find(c=>!player.profile.team.includes(c.id));await click('[data-act="detail"][data-id="'+first.id+'"]');await click('[data-act="rune-upgrade"][data-id="'+first.id+'"][data-kind="guard"]');assert.equal(player.profile.collection[0].rune.kind,'guard');await shot('specialization');await click('[data-act="detail"][data-id="'+extra.id+'"]');await click('[data-act="legacy-review"][data-id="'+extra.id+'"]');await shot('legacy-confirm');await click('[data-act="legacy-cancel"]');assert(player.profile.collection.some(c=>c.id===extra.id));await click('[data-act="legacy-review"][data-id="'+extra.id+'"]');await click('[data-act="legacy-confirm"]');assert(!player.profile.collection.some(c=>c.id===extra.id));await click('[data-act="close-panel"]');
 await click('[data-value="ecology"]');assert(await f.locator('.eco-recipes article').count()===6);await click('[data-act="craft"][data-id="bait"]');assert.equal(player.profile.resources.bait,1);await shot('notebook-desktop');await click('[data-act="close-panel"]');
 const site=E.landmarks('forest').find(s=>s.siteId==='sap');await move(site);await shot('sap-grove');await click('[data-act="lure"]');assert.equal(player.profile.resources.bait,0);assert(room.spawns.some(s=>s.lured));
 const lure=room.spawns.find(s=>s.lured);await move(lure);await f.evaluate(id=>InsectApp.ui.setSelection({type:'spawn',id}),lure.id);await click('[data-act="encounter"]');await f.evaluate(()=>InsectApp.send('auto-battle',{enabled:false}));const record=room.battles.get(player.battleId);record.state.sides.b.team[0].hp=1;record.state.sides.a.team[0].speed=999;await f.waitForFunction(()=>!InsectApp.isAnimating());await click('[data-action="attack"]');await f.waitForFunction(()=>!InsectApp.isAnimating()&&InsectApp.getSnapshot().battle.status==='finished',null,{timeout:20000});if(await f.locator('[data-act="close-reward"]').count())await click('[data-act="close-reward"]');await click('[data-act="return"]');assert.equal(player.profile.ecology.wins,1);
 const node=room.resources.find(n=>n.regionId==='forest'&&n.kind==='mushroom'&&n.available!==false);await move(node);await f.evaluate(id=>InsectApp.ui.setSelection({type:'resource',id}),node.id);await click('[data-act="gather"]');assert.equal(player.profile.ecology.gathered,1);if(await f.locator('[data-act="close-reward"]').count())await click('[data-act="close-reward"]');
 const event=await f.evaluate(()=>InsectApp.getSnapshot().ecology.event);await move(event);await shot('discovery');await click('[data-act="explore-event"]');assert.equal(player.profile.ecology.events,1);
 // Tour the map with the real scene; check the paths are above sampled mesh heights.
 await move({x:-25,z:-4});await shot('forest-hills');
 const terrain=await f.evaluate(()=>{const scene=InsectApp.world.scene,ground=scene.getMeshByName('region-terrain');return {paths:scene.meshes.filter(m=>m.name.startsWith('ecology-trail')).length,heights:[[-82,-40],[0,68],[72,-72]].map(([x,z])=>ground.getHeightAtCoordinates(x,z)),meshes:scene.meshes.length,fps:scene.getEngine().getFps()};});assert.equal(terrain.paths,3);assert(terrain.heights[0]-terrain.heights[1]>25);console.log('지형',JSON.stringify(terrain));
 for(const size of [{width:844,height:390},{width:390,height:844}]){await page.setViewportSize(size);await click('[data-value="ecology"]');const bounds=await f.evaluate(()=>{const r=document.querySelector('.ix-drawer').getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:innerWidth,h:innerHeight,scroll:document.documentElement.scrollWidth};});assert(bounds.x>=0&&bounds.y>=0&&bounds.right<=bounds.w+1&&bounds.bottom<=bounds.h+1,JSON.stringify(bounds));assert(bounds.scroll<=bounds.w+1);await shot('notebook-mobile-'+size.width);await click('[data-act="close-panel"]');await shot('field-mobile-'+size.width);}
 await page.setViewportSize({width:1440,height:1000});await page.reload();f=await(await page.locator('#game-frame').elementHandle()).contentFrame();await f.waitForFunction(()=>window.InsectApp?.ready,null,{timeout:60000});assert.equal(await f.evaluate(()=>InsectApp.getSnapshot().profile.ecology.events),1);assert.equal(await f.evaluate(()=>InsectApp.getSnapshot().profile.ecology.gathered),1);assert.equal(await f.evaluate(()=>InsectApp.getSnapshot().profile.adventurerName),'하나');
 assert.equal(await f.evaluate(()=>InsectApp.getSnapshot().profile.trials.cleared),1);await click('[data-value="housing"]');await click('[data-act="home-travel"][data-id="quarry"]');assert.equal(player.mount,'motorcycle');const stone=room.resources.find(n=>n.regionId==='quarry');await move(stone);await f.evaluate(id=>InsectApp.ui.setSelection({type:'resource',id}),stone.id);await f.locator('[data-act="gather"]').click();await f.waitForFunction(()=>!!InsectApp.getSnapshot().players.find(p=>p.uid===InsectApp.getSnapshot().you).harvest);assert.equal(player.mount,'');await f.waitForFunction(()=>!InsectApp.getSnapshot().players.find(p=>p.uid===InsectApp.getSnapshot().you).harvest);assert.equal(player.mount,'motorcycle');if(await f.locator('[data-act="close-reward"]').count())await click('[data-act="close-reward"]');await click('[data-act="town-return"]');assert.equal(player.regionId,'safe');assert.equal(player.mount,'motorcycle');
 assert.deepEqual(errors,[]);console.log('탐험 UI 통과: 데스크톱·모바일 가로/세로, 제작·유인·채집·현장 사건·저장 복원·한글·콘솔');
}catch(e){if(page)await page.screenshot({path:path.join(out,'ecology-failure.png')}).catch(()=>{});throw e;}finally{await browser?.close();await game.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
