'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createGameServer}=require('../server/index.cjs'),H=require('../shared/housing.js');
const out=path.join(__dirname,'../test-output');fs.mkdirSync(out,{recursive:true});
const game=createGameServer({authority:{verifyToken:async token=>({uid:token}),getRoom:async()=>({gameType:'insectExpedition',status:'playing',players:{alice:{nickname:'하나'},bob:{nickname:'두리'}}})},dbPath:path.join(fs.mkdtempSync(path.join(os.tmpdir(),'housing-ui-')),'db.json')});let browser,page;
(async()=>{try{
 const seeded=await game.store.get('alice');seeded.gold=6000;seeded.resources.wood=40;seeded.resources.stone=30;seeded.resources.sand=20;await game.store.save(seeded);
 const address=await game.listen(0,'127.0.0.1');browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
 async function open(uid,mobile){const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:800},isMobile:mobile,hasTouch:mobile});await context.addInitScript(uid=>window.fixtureUid=uid,uid);
  await context.route('https://www.gstatic.com/firebasejs/**',route=>route.fulfill({contentType:'text/javascript',body:`window.firebase ||= {apps:[{}],auth:()=>({onAuthStateChanged(fn){queueMicrotask(()=>fn({uid:window.fixtureUid,getIdToken:async()=>window.fixtureUid}));return ()=>{};}}),database:()=>({ref:()=>({once:async()=>({val:()=>({gameType:'insectExpedition',status:'playing',players:{alice:{nickname:'하나'},bob:{nickname:'두리'}}})})})})};`}));
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:'+address.port+'/insect_expedition/index.html?roomId=homes');const frame=await(await page.locator('#game-frame').elementHandle()).contentFrame();await frame.waitForFunction(()=>window.InsectApp?.ready);await frame.locator('#explorer-name').fill(uid==='alice'?'하나':'두리');await frame.locator('#enter-world').click();await page.waitForTimeout(650);return {page,frame};
 }
 const a=await open('alice',true);page=a.page;const f=a.frame,room=game.rooms.get('homes'),player=room.players.get('alice');
 async function click(selector){await f.locator(selector).first().click();await page.waitForTimeout(650);}
 const send=(name,payload={})=>f.evaluate(({name,payload})=>InsectApp.send(name,payload),{name,payload});
 for(const size of [{width:844,height:390},{width:390,height:844},{width:1280,height:800}]){await page.setViewportSize(size);await page.waitForTimeout(500);assert(await f.evaluate(()=>{const a=document.querySelector('.ix-top').getBoundingClientRect(),b=document.querySelector('.ix-nav').getBoundingClientRect();return a.left>=0&&a.right<=innerWidth&&b.left>=0&&b.right<=innerWidth;}));await page.screenshot({path:path.join(out,'housing-hud-'+size.width+'.png')});}
 await page.setViewportSize({width:844,height:390});
 await click('[data-value="shop"]');await click('[data-act="buy"][data-id="deed-small"]');assert.equal(player.profile.bag.deeds.small,1);assert.equal(player.profile.gold,4000);await click('[data-act="close-panel"]');
 await click('[data-value="bag"]');assert.match(await f.locator('.ix-bag-grid').innerText(),/5평 땅문서/);await page.screenshot({path:path.join(out,'housing-bag.png')});await click('[data-act="deed-use"]');
 await f.locator('[aria-label="토지 선택"]').waitFor();assert.equal(await f.evaluate(()=>InsectApp.world.scene.meshes.filter(m=>m.name.startsWith('available-land-')&&m.isEnabled()).length),3);await page.screenshot({path:path.join(out,'housing-green-plots.png')});
 const plotClick=await f.evaluate(()=>{const scene=InsectApp.world.scene,m=scene.getMeshByName('available-land-meadow');const p=BABYLON.Vector3.Project(m.getAbsolutePosition(),BABYLON.Matrix.Identity(),scene.getTransformMatrix(),scene.activeCamera.viewport.toGlobal(innerWidth,innerHeight));return {x:p.x,y:p.y};});await f.locator('#game-canvas').click({position:plotClick});await page.waitForTimeout(400);assert.equal(await f.locator('[data-act="home-site"][data-id="meadow"]').getAttribute('aria-pressed'),'true');assert.equal(await f.locator('.ix-nav').isVisible(),false);
 await click('[data-act="home-cancel"]');assert.equal(player.profile.bag.deeds.small,1);await click('[data-value="bag"]');await click('[data-act="deed-use"]');await click('[data-act="home-site"][data-id="meadow"]');await click('[data-act="land-confirm"]');assert.equal(player.profile.housing.plot.siteId,'meadow');assert.equal(player.profile.bag.deeds.small,0);await f.locator('[aria-label="집 건축"]').waitFor();
 // 바닥 4칸과 문·창문·지붕·가구를 실제 건축 버튼으로 설치한다.
 await click('[data-act="build-place"]');await click('[data-act="build-nudge"][data-x="1"]');await click('[data-act="build-place"]');await click('[data-act="build-nudge"][data-z="1"]');await click('[data-act="build-place"]');await click('[data-act="build-nudge"][data-x="-1"]');await click('[data-act="build-place"]');
 await click('[data-act="build-nudge"][data-z="-1"]');await click('[data-act="build-part"][data-id="door"]');await click('[data-act="build-place"]');await click('[data-act="build-nudge"][data-x="1"]');await click('[data-act="build-part"][data-id="window"]');await click('[data-act="build-place"]');await click('[data-act="build-part"][data-id="roof"]');await click('[data-act="build-place"]');const roofPiece=player.profile.housing.pieces.find(p=>p.kind==='roof');await f.locator('[data-home-piece]').selectOption(roofPiece.id);await click('[data-act="build-remove"]');assert(!player.profile.housing.pieces.some(p=>p.id===roofPiece.id));await click('[data-act="build-place"]');await click('[data-act="build-nudge"][data-z="1"]');await click('[data-act="build-part"][data-id="bed"]');await click('[data-act="build-place"]');
 assert.equal(player.profile.housing.pieces.length,8);await page.screenshot({path:path.join(out,'housing-build-mobile.png')});await click('[data-act="home-cancel"]');
 // 도어 메시 선택 → 문 열기 → 실내 진입과 지붕 가림.
 const door=player.profile.housing.pieces.find(p=>p.kind==='door'),pos=H.point(player.profile.housing.plot,door);player.x=pos.x;player.z=pos.z-4;await page.waitForTimeout(1150);await f.evaluate(()=>{InsectApp.world.camera.alpha=Math.PI/2;document.activeElement.blur();});await page.keyboard.down('ArrowDown');await page.waitForTimeout(850);await page.keyboard.up('ArrowDown');await page.waitForTimeout(200);assert(player.z<pos.z-1.8,'닫힌 문이 이동을 막아야 합니다.');
 await f.evaluate(id=>InsectApp.ui.setSelection({type:'home-piece',id}),door.id);await f.waitForFunction(id=>InsectApp.getSnapshot().home.pieces.find(p=>p.id===id)?.open,door.id);assert(player.profile.housing.pieces.find(p=>p.id===door.id).open);
 await page.keyboard.down('ArrowDown');await page.waitForTimeout(420);await page.keyboard.up('ArrowDown');await page.waitForTimeout(600);assert(player.z>pos.z-1.1,'문을 열면 키보드 이동으로 실내 진입해야 합니다.');assert(await f.evaluate(()=>InsectApp.world.scene.transformNodes.filter(n=>n.metadata?.kind==='roof').every(n=>!n.isEnabled())));await page.screenshot({path:path.join(out,'housing-interior.png')});
 // 각 자재 채집장으로 이동하고 실제 도구 모션·획득창·가방 증가 확인.
 for(const [camp,kind] of [['lumber','wood'],['quarry','stone'],['sandpit','sand']]){
  await click('[data-value="housing"]');await click('[data-act="home-travel"][data-id="'+camp+'"]');const before=player.profile.resources[kind];
  await f.locator('[data-act="gather"]').click();await f.locator('.ix-harvest:not([hidden])').waitFor();await page.waitForTimeout(500);
  assert(await f.evaluate(()=>InsectApp.world.scene.getTransformNodeByName('harvest-tool')!==null));await page.screenshot({path:path.join(out,'housing-harvest-'+kind+'.png')});
  await f.locator('[aria-label="획득 알림"]').waitFor({timeout:10000});assert(player.profile.resources[kind]>before);await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'housing-earned-'+kind+'.png')});await click('[data-act="close-reward"]');
 }
 await click('[data-value="housing"]');await click('[data-act="home-travel"][data-id="home"]');
 const second=await open('bob',false);await second.frame.locator('[data-value="housing"]').click();await second.page.waitForTimeout(650);await second.frame.locator('[data-act="home-visit"]').click();await second.frame.waitForFunction(()=>InsectApp.getSnapshot().realm==='alice');assert.equal(room.players.get('bob').realm,'alice');await second.page.screenshot({path:path.join(out,'housing-friend-desktop.png')});
 const persisted=JSON.parse(JSON.stringify(player.profile.housing));await page.reload();const again=await(await page.locator('#game-frame').elementHandle()).contentFrame();await again.waitForFunction(()=>window.InsectApp?.ready);assert.deepEqual(await again.evaluate(()=>InsectApp.getSnapshot().profile.housing),persisted);
 assert.deepEqual(errors,[]);console.log('주택 화면 검증 통과: 3개 화면 비율·가방·초록 부지·취소/확정·8개 건축물·문·실내 지붕·벌목/채광/모래 모션 및 중앙 획득·친구 방문·재접속 저장.');
}catch(e){if(page)await page.screenshot({path:path.join(out,'housing-failure.png')}).catch(()=>{});throw e;}finally{await browser?.close();await game.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
