'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const WebSocket = require('ws');
const { createGameServer } = require('../server/index.cjs');
const { createStore } = require('../server/data-store.cjs');
const Data = require('../shared/data.js');
const World = require('../server/world.cjs');

test('실제 채집 3회 → 보상 중복 방지 → 먹이 3개 → 진화 → 재시작 후 복원 → 반복 의뢰', async t => {
  const dbPath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'insect-progress-')), 'profiles.json');
  const authority = { verifyToken: async () => ({ uid: 'quest-user' }), getRoom: async () => ({ gameType: 'insectExpedition', status: 'playing', players: { 'quest-user': { nickname: '퀘스트 검증' } } }) };
  let now = Date.now();
  const game = createGameServer({ authority, dbPath, rng: () => 0, now: () => now });
  const address = await game.listen(0, '127.0.0.1');
  t.after(() => game.close());
  const ws = new WebSocket(`ws://127.0.0.1:${address.port}/insect_expedition/ws`);
  t.after(() => ws.terminate());
  await new Promise(resolve => ws.once('open', resolve));
  let sequence = 0;
  const waiting = new Map();
  ws.on('message', raw => { const m = JSON.parse(raw); if (m.type === 'ack') { waiting.get(m.id)?.(m); waiting.delete(m.id); } });
  function send(message) { return new Promise(resolve => { waiting.set(message.id || 'join', resolve); ws.send(JSON.stringify(message)); }); }
  async function command(name, payload = {}, id = 'c' + (++sequence)) {
    now += 1600;
    const ack = await send({ type: 'command', id, name, payload });
    assert.equal(ack.ok, true, ack.error);
    return ack.result;
  }
  assert.equal((await send({ type: 'join', roomId: 'quest-room', token: 'fixture' })).ok, true);
  const player = game.rooms.get('quest-room').players.get('quest-user');
  player.x=50;player.z=40;
  await command('quest');
  assert.deepEqual({x:player.x,z:player.z},{x:50,z:40},'현재 위치에서 퀘스트 수락, 강제 이동 없음');
  await command('character',{id:'scout',name:'숲탐험가'});
  assert.equal(player.nickname,'숲탐험가');
  now+=1600;
  const invalidName=await send({type:'command',id:'bad-name',name:'character',payload:{id:'scout',name:'abcdefg'}});
  assert.equal(invalidName.ok,false);
  assert.equal(createStore({dbPath}).get('quest-user').adventurerName,'숲탐험가');
  const targets = game.rooms.get('quest-room').spawns.filter(s => ['tutorial-6','tutorial-1','tutorial-2'].includes(s.id));
  for (const target of targets) {
    player.x = target.x; player.z = target.z;
    const beforeCount = player.profile.collection.length;
    const entered = await command('collect', { spawnId: target.id });
    assert.equal(player.profile.collection.length, beforeCount, '전투 없이 채집되지 않음');
    let battle = game.rooms.get('quest-room').battles.get(entered.battleId);
    for (let turn = 0; turn < 30 && battle.state.status === 'active'; turn++) await command('action', {battleId:battle.id,turn:battle.state.turn,action:{type:'attack'}});
    assert.equal(battle.state.result.winner, 'a');
    assert.equal(battle.state.result.captureSummary.success, true);
    assert.equal(player.profile.collection.length, beforeCount + 1);
    assert(player.profile.collection.every(c => c.hp > 0));
    await command('return');
  }
  assert.equal(player.profile.quest.status, 'ready');
  await command('travel', { biomeId: 'safe' });
  await command('quest', {}, 'claim-once');
  await command('quest', {}, 'claim-once');
  assert.equal(player.profile.supplies.feeds, 6);
  // A captured larva starts at Lv.1; its actual growth and evolved move set are checked.
  const larva = game.store.createCreature('moss_caterpillar', 1);
  player.profile.collection.push(larva);
  player.profile = await game.store.save(player.profile);
  const oldAttack = Data.speciesById[larva.speciesId].normalAttack.id;
  for (let i = 0; i < 3; i++) await command('feed', { creatureId: larva.id });
  const evolved = (await command('evolve', { creatureId: larva.id })).creature;
  assert.equal(evolved.level, 5);
  assert.equal(evolved.speciesId, 'moon_moth');
  assert.notEqual(Data.speciesById[evolved.speciesId].normalAttack.id, oldAttack);
  assert.ok(Data.speciesById[evolved.speciesId].skill);
  const restored = createStore({ dbPath }).get('quest-user');
  assert.equal(restored.collection.find(c => c.id === larva.id).speciesId, 'moon_moth');
  assert.equal(restored.supplies.feeds, 3);
  assert.equal(restored.quest.completed, 1);
  assert.equal((await command('quest')).quest.status, 'active');
  assert.equal(player.profile.quest.progress, 0);
  assert.equal(player.profile.quest.id, 'battle-practice');
  const unread = player.profile.discoveries.filter(id => !player.profile.encyclopedia.seen.includes(id));
  assert(unread.includes('moss_caterpillar')); assert(unread.includes('moon_moth'));
  const claimed = await command('dex-claim', {}, 'dex-once');
  const savedFeed = player.profile.supplies.feeds;
  assert(claimed.feeds > 6, '새 도감과 수집 단계 보상');
  await command('dex-claim', {}, 'dex-once');
  await command('dex-claim');
  assert.equal(player.profile.supplies.feeds, savedFeed, '요청 ID와 상관없이 도감 중복 보상 방지');
  await command('dex-seen', {ids:player.profile.discoveries});
  assert.deepEqual(new Set(player.profile.encyclopedia.seen), new Set(player.profile.discoveries));
  assert.deepEqual(createStore({dbPath}).get('quest-user').encyclopedia, player.profile.encyclopedia);
  // A fresh defeat restores every teammate and permits an immediate next encounter.
  const target = game.rooms.get('quest-room').spawns.find(s => s.id === 'tutorial-3');
  player.x=target.x;player.z=target.z;
  const entered=await command('encounter',{spawnId:target.id});
  const battle=game.rooms.get('quest-room').battles.get(entered.battleId);
  battle.state.sides.a.team.forEach(c=>{c.hp=1;c.speed=0;});
  battle.state.sides.b.team[0].attack=500;
  for(let n=0;n<6&&battle.state.status==='active';n++) await command('action',{battleId:battle.id,turn:battle.state.turn,action:{type:'attack'}});
  assert.equal(battle.state.result.winner,'b');
  assert.equal(battle.state.result.recovered,true);
  assert(player.profile.collection.every(c=>c.hp===require('../shared/battle.cjs').statsForCreature(c).maxHealth));
  await command('return');
  const next=game.rooms.get('quest-room').spawns.find(s=>s.id==='tutorial-4');player.x=next.x;player.z=next.z;
  assert((await command('encounter',{spawnId:next.id})).battleId);
  const again=game.rooms.get('quest-room').battles.get(player.battleId);
  await command('action',{battleId:again.id,turn:again.state.turn,action:{type:'retreat'}});await command('return');
  const ids=player.profile.team.slice().reverse();await command('team',{ids});assert.deepEqual(player.profile.team,ids);
  assert.deepEqual(createStore({dbPath}).get('quest-user').team,ids);
});
