'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createGameServer}=require('../server/index.cjs'),R=require('../shared/regions.js');
const out=path.join(__dirname,'../test-output');fs.mkdirSync(out,{recursive:true});
const game=createGameServer({rng:()=>.43,authority:{verifyToken:async token=>({uid:token}),getRoom:async()=>({gameType:'insectExpedition',status:'playing',players:{alice:{nickname:'하나'}}})},dbPath:path.join(fs.mkdtempSync(path.join(os.tmpdir(),'regions-ui-')),'db.json')});let browser,page;
(async()=>{try{
 const profile=game.store.get('alice');profile.adventurerName='하나';profile.characterCreated=true;profile.resources.wood=25;profile.resources.stone=15;profile.resources.sand=20;profile.collection[0].speciesId='moon_moth';profile.collection[0].level=5;profile.collection[0].hp=null;profile.team=[profile.collection[0].id];game.store.save(profile);
 const address=await game.listen(0,'127.0.0.1');browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const errors=[];
 await context.route('https://www.gstatic.com/firebasejs/**',route=>route.fulfill({contentType:'text/javascript',body:`window.firebase ||= {apps:[{}],auth:()=>({onAuthStateChanged(fn){queueMicrotask(()=>fn({uid:'alice',getIdToken:async()=> 'alice'}));return ()=>{};}}),database:()=>({ref:()=>({once:async()=>({val:()=>({gameType:'insectExpedition',status:'playing',players:{alice:{nickname:'하나'}}})})})})};`}));
 page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:'+address.port+'/insect_expedition/index.html?roomId=regions');const f=await(await page.locator('#game-frame').elementHandle()).contentFrame();await f.waitForFunction(()=>window.InsectApp?.ready);await f.locator('[data-act="customize"]').waitFor();
 const room=game.rooms.get('isulsup-public'),player=room.players.get('alice'),send=(name,payload={})=>f.evaluate(({name,payload})=>InsectApp.send(name,payload),{name,payload});
 async function click(selector){await f.locator(selector).first().click();await page.waitForTimeout(350);}
 async function shot(name){await page.screenshot({path:path.join(out,'regions-'+name+'.png')});}
 async function travel(to){await click('.ix-nav [data-value="map"]');await click('[data-act="map-travel"][data-id="'+to+'"]');await f.waitForFunction(id=>InsectApp.getSnapshot().regionId===id,to);await page.waitForTimeout(1000);}
 async function drawerBounds(){assert(await f.evaluate(()=>{const el=document.querySelector('.ix-drawer'),r=el.getBoundingClientRect();return Math.abs((r.left+r.right)/2-innerWidth/2)<2&&Math.abs((r.top+r.bottom)/2-innerHeight/2)<2&&r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}),'메뉴는 화면 중앙 안에 있어야 합니다.');}
 await page.waitForTimeout(500);assert.equal(await f.evaluate(()=>InsectApp.getSnapshot().spawns.length),0);await shot('village-desktop');
 const box=await f.locator('#game-canvas').boundingBox();async function drag(button){await page.mouse.move(box.x+box.width*.46,box.y+box.height*.45);await page.mouse.down({button});await page.mouse.move(box.x+box.width*.56,box.y+box.height*.47,{steps:12});await page.mouse.up({button});}
 const before=await f.evaluate(()=>InsectApp.world.camera.alpha);await drag('left');assert(Math.abs(await f.evaluate(()=>InsectApp.world.camera.alpha)-before)<.01);await drag('right');assert(Math.abs(await f.evaluate(()=>InsectApp.world.camera.alpha)-before)>.2);
 await click('[data-value="housing"]');await drawerBounds();assert(await f.evaluate(()=>document.querySelector('.ix-drawer').getBoundingClientRect().height<innerHeight-150));await shot('housing-desktop');await click('[data-act="close-panel"]');
 await click('[data-value="shop"]');await drawerBounds();await click('[data-act="sell-resource"][data-id="wood"][data-count="10"]');assert.equal(player.profile.resources.wood,15);assert.equal(player.profile.gold,80);await shot('sale-desktop');await click('[data-act="close-panel"]');
 await travel('grassland');assert(await f.evaluate(()=>InsectApp.getSnapshot().spawns.every(s=>s.biomeId==='grassland')));await shot('grassland');
 // Actual height follows the same terrain function used to build the ground mesh.
 player.x=80;player.z=100;await page.waitForTimeout(1200);assert(await f.evaluate(()=>{const a=InsectApp.world.scene.getTransformNodeByName('avatar-local');return Math.abs(a.position.y-InsectRegions.terrain('grassland',a.position.x,a.position.z)-.4)<.2;}));
 const spawn=room.spawns.find(s=>s.id==='tutorial-1');player.x=spawn.x+2;player.z=spawn.z;await page.waitForTimeout(1200);await send('sprint',{enabled:true});await f.evaluate(id=>InsectApp.ui.setSelection({type:'spawn',id}),spawn.id);await f.locator('[data-act="encounter"]').click();await f.waitForFunction(()=>!!InsectApp.getSnapshot().battle);await shot('battle-entry');await send('auto-battle',{enabled:false});await page.waitForTimeout(900);
 await f.waitForFunction(()=>InsectAudio.getStatus().state==='running'&&InsectAudio.getStatus().rms>0.0001);await f.evaluate(()=>{window.peakParticles=0;window.particleObserver=InsectApp.world.scene.onBeforeRenderObservable.add(()=>{window.peakParticles=Math.max(window.peakParticles,...InsectApp.world.scene.particleSystems.map(p=>p.getActiveCount()),0);});});
 await f.locator('[data-action="skill"]').click();await page.waitForTimeout(600);await shot('skill-particles');await f.waitForFunction(()=>window.peakParticles>0);await f.waitForFunction(()=>!InsectApp.isAnimating(),null,{timeout:18000});
 if(player.battleId){const rec=room.battles.get(player.battleId);if(rec.state.status==='active'){await f.locator('[data-action="retreat"]').click();await f.waitForFunction(()=>!InsectApp.isAnimating()&&InsectApp.getSnapshot().battle.status==='finished',null,{timeout:18000});}}
 if(await f.locator('[data-act="close-reward"]').count())await click('[data-act="close-reward"]');await click('[data-act="return"]');assert(player.sprinting);await f.waitForFunction(()=>InsectApp.getSnapshot().players.find(p=>p.uid===InsectApp.getSnapshot().you).sprinting);
 for(const region of ['forest','rock','wetland','cave','farm','facility']){await travel('safe');await travel(region);await shot(region);assert.equal(await f.evaluate(()=>InsectApp.world.scene.transformNodes.filter(n=>n.name.startsWith('region-')&&n.name!=='region-tree').length)>0,true);}
 await send('home-travel',{destination:'lumber'});await page.waitForTimeout(1000);await f.locator('[data-act="gather"]').click();await f.locator('[data-act="close-reward"]').click({timeout:10000});assert(player.profile.resources.wood>15);
 for(const size of [{width:844,height:390},{width:390,height:844}]){await page.setViewportSize(size);await page.waitForTimeout(400);await click('[data-value="housing"]');await drawerBounds();await shot('housing-'+size.width);await click('[data-act="close-panel"]');await click('[data-value="map"]');await drawerBounds();await shot('map-'+size.width);await click('[data-act="close-panel"]');}
 await page.reload();const again=await(await page.locator('#game-frame').elementHandle()).contentFrame();await again.waitForFunction(()=>window.InsectApp?.ready);assert.equal(await again.evaluate(()=>InsectApp.getSnapshot().regionId),'lumber');assert.deepEqual(errors,[]);console.log('지역·전투 화면 검증 통과: 포탈 분리/지형 높이/PC 우클릭/중앙 메뉴/자재 판매/전투 진입/실제 오디오 파형/스킬 파티클/달리기 유지/모바일 가로세로/재접속 지역 복원.');
}catch(e){if(page)await page.screenshot({path:path.join(out,'regions-failure.png')}).catch(()=>{});throw e;}finally{await browser?.close();await game.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
