'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),WS=require('ws');
const D=require('../shared/data.js'),T=require('../shared/trials.js'),B=require('../shared/battle.cjs'),{createGameServer}=require('../server/index.cjs');
test('특화는 실전 능력치를 바꾸고 진화 후에도 유지된다',()=>{
 const c={id:'c',speciesId:'cave_stag',level:30,rune:{kind:'guard',level:3}},plain=B.statsForCreature({...c,rune:null}),up=B.statsForCreature(c);assert(up.maxHealth>plain.maxHealth);assert(up.defense>plain.defense);assert.equal(up.attack,plain.attack);assert.deepEqual(B.evolveCreature(c).rune,c.rune);assert.equal(T.normalize({cleared:999}).cleared,24);
});
test('시련 해금·첫 보상·중복 전설 연구·특화 저장·귀환 및 채집 재탑승',async()=>{
 let now=Date.now(),seq=0;const game=createGameServer({now:()=>now,rng:()=>0,authority:{verifyToken:async uid=>({uid}),getRoom:async()=>({gameType:'insectExpedition',status:'playing',players:{alice:{nickname:'하나'}}})},dbPath:path.join(fs.mkdtempSync(path.join(os.tmpdir(),'trials-')),'db.json')});let ws;
 try{const address=await game.listen(0,'127.0.0.1');ws=new WS('ws://127.0.0.1:'+address.port+'/insect_expedition/ws');const pending=new Map();ws.on('message',raw=>{const m=JSON.parse(raw);if(m.type==='ack')pending.get(m.id)?.(m);});await new Promise(r=>ws.once('open',r));function request(m){return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('응답 시간 초과')),3000);pending.set(m.id||'join',v=>{clearTimeout(t);pending.delete(m.id||'join');resolve(v);});ws.send(JSON.stringify(m));});}assert((await request({type:'join',token:'alice',roomId:'test'})).ok);
 const room=game.rooms.get('test'),p=room.players.get('alice');async function cmd(name,payload={},ok=true,id='c'+(++seq)){now+=1600;const ack=await request({type:'command',name,payload,id});assert.equal(ack.ok,ok,ack.error);return ack.result;}
 p.profile.collection.forEach(c=>{c.speciesId='king_stag';c.level=30;c.hp=null;});const extra=game.store.createCreature('king_stag',5);p.profile.collection.push(extra);p.profile.mounts={owned:['motorcycle'],equipped:'motorcycle'};p.mount='motorcycle';
 await cmd('legacy-research',{creatureId:extra.id},false);await cmd('legacy-research',{creatureId:p.profile.team[0],confirm:true},false);
 const save=game.store.save,before=JSON.stringify(p.profile);game.store.save=()=>{throw Error('모의 저장 실패');};await cmd('legacy-research',{creatureId:extra.id,confirm:true},false);assert.equal(JSON.stringify(p.profile),before);game.store.save=save;
 await cmd('legacy-research',{creatureId:extra.id,confirm:true},true,'research-once');await cmd('legacy-research',{creatureId:extra.id,confirm:true},true,'research-once');assert.equal(p.profile.resources.shard,5);assert.equal(p.profile.collection.length,3);
 await cmd('rune-upgrade',{creatureId:p.profile.team[0],kind:'guard'});assert.equal(p.profile.resources.shard,2);await cmd('rune-upgrade',{creatureId:p.profile.team[0],kind:'guard'},false);await cmd('rune-upgrade',{creatureId:p.profile.team[0],kind:'swift'});assert.equal(p.profile.resources.shard,1);assert.equal(p.profile.collection[0].rune.kind,'swift');
 await cmd('trial-start',{stage:2},false);await cmd('trial-start',{stage:1});let record=room.battles.get(p.battleId);assert.equal(record.state.trial.stage,1);assert.equal(record.state.sides.b.team.length,3);assert(record.state.sides.b.team[0].speed>B.statsForCreature({speciesId:'honey_mason_bee',level:22}).speed);
 async function win(){const r=room.battles.get(p.battleId);r.state.sides.b.team.forEach(c=>{c.hp=1;c.attack=1;});r.state.sides.a.team.forEach(c=>{c.hp=c.maxHp;c.speed=999;c.attack=999;});for(let i=0;i<8&&r.state.status==='active';i++)await cmd('action',{battleId:r.id,turn:r.state.turn,action:{type:'attack'}});assert.equal(r.state.result.winner,'a');await cmd('return');return r;}
 const count=p.profile.collection.length;record=await win();assert.equal(p.profile.trials.cleared,1);assert.equal(p.profile.resources.shard,4);assert.equal(p.profile.collection.length,count);assert(!record.state.result.captureSummary);
 await cmd('trial-start',{stage:1});record=await win();assert.equal(record.state.result.shards,0);assert.equal(p.profile.resources.shard,4);await cmd('trial-start',{stage:3},false);
 await cmd('trial-start',{stage:2});record=room.battles.get(p.battleId);await cmd('action',{battleId:record.id,turn:record.state.turn,action:{type:'retreat'}});await cmd('return');assert.equal(p.profile.trials.cleared,1);
 await cmd('home-travel',{destination:'lumber'});assert.equal(p.mount,'motorcycle');const wood=room.resources.find(n=>n.regionId==='lumber');p.x=wood.x;p.z=wood.z;await cmd('gather-start',{nodeId:wood.id});assert.equal(p.mount,'');await cmd('gather-cancel');assert.equal(p.mount,'motorcycle');
 await cmd('gather-start',{nodeId:wood.id});now+=2500;await cmd('gather',{nodeId:wood.id});assert.equal(p.mount,'motorcycle');assert.equal(p.profile.mounts.equipped,'motorcycle');await cmd('home-travel',{destination:'quarry'});assert.equal(p.mount,'motorcycle');await cmd('home-travel',{destination:'home'});assert(p.realm);await cmd('home-travel',{destination:'field'});assert.equal(p.regionId,'safe');assert.equal(p.realm,'');assert.equal(p.mount,'motorcycle');
 const saved=game.store.get('alice');assert.equal(saved.trials.cleared,1);assert.deepEqual(saved.collection[0].rune,{kind:'swift',level:1});assert.equal(saved.resources.shard,4);assert.equal(saved.mounts.equipped,'motorcycle');
 }finally{ws?.close();await game.close();}
});
